export const Patterns = {
    amLetters_space: /^[Ա-Ֆա-և- ]+$/,
    AmLetters_Space_Description: /^[Ա-Ֆա-և- ]+$^$|/,
    only_digits: /^-?[0-9]+$/,
    length: /^\d{10}$/,
    amEnLetters_socialGroup: /^(?=.*[Ա-և])[Ա-և- ․().«»<>,/0-9]+$/,
    amEnLetters_Group: /^(?=.*[Ա-և])[Ա-և- ]+$/,
    enLetters_digits: /^[A-Z]{2}[0-9]{7}$/,
    enLetters: /^[A-Z]+$/,
    cityphone: /^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{3})$/,
    mobile: /^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{3})$/,
    digits: /^[0-9]+$/,
    email: /^[\w-\.]+@([\w-]+\.)+[\w-]{2,4}$/,
    passportNumber: /^[A-Za-zА-Яа-я0-9]{2,15}$/,
    fromWho: /^[0-9]{3}$/,
    birthNumber: /^[Ա-ՖА-ЯA-Z0-90-9]{2,15}$/,
    socialCardNumber: /^\d{10}$/,
    description: /^[Ա-Ֆա-և-][0-9]+$/,
    phoneNumber: /^[0-9+]{6,20}$/,
    deadNumber: /^[A-Za-zА-Яа-яԱ-Ֆա-և0-9]{2,15}$/,
    certificate_number : /^[A-ZА-Я]{2}[0-9]{6,13}$/,
}